# Generated by Django 5.2.4 on 2025-07-30 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("course_card", models.ImageField(upload_to="img/course_cards/")),
                ("description", models.TextField()),
                ("video_link", models.URLField()),
                ("goals", models.JSONField(blank=True, default=list)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("exercises", models.JSONField(blank=True, default=list)),
                ("activities", models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
