# Generated by Django 5.2.4 on 2025-07-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_usercourseprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="chapter",
            field=models.IntegerField(default=1),
        ),
    ]
